import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { toast } from "sonner";
import { AdminGate } from "@/components/AdminGate";
import { AuComplianceShell } from "@/components/AuComplianceShell";
import { EmptyState, KpiTile, SectionCard, StatusChip } from "@/components/monday";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useMyTenantCountry, useMyTenantId } from "@/hooks/use-tenant";
import {
  buildSuperBatch,
  listSuperBatches,
  markSuperBatchPaid,
  submitSuperBatch,
} from "@/lib/super.functions";
import { getSuperSlaSummary } from "@/lib/super-sla.functions";
import { AlertTriangle, Download, Send } from "lucide-react";

/**
 * Payday Super remittance (PRD M4).
 *
 * Eight server functions existed for this and nothing called any of them, so a
 * contribution generated by an approved payroll run had no path to a clearing
 * house at all. The SLA sweep that reports overdue money was equally
 * unreachable, which is why it leads the page rather than hiding in a tab: an
 * overdue super payment is a director-liability matter, not a list item.
 *
 * Gated `org.auSuperBatches` (org_admin, finance), mirroring
 * `super_batches finance write`. Narrower than the funds page on purpose —
 * HR maintains the register, finance moves the money.
 */
export const Route = createFileRoute("/admin/super-batches")({
  head: () => ({ meta: [{ title: "Payday Super — HRPPL" }] }),
  component: () => (
    <AdminGate feature="org.auSuperBatches">
      <SuperBatchesPage />
    </AdminGate>
  ),
});

const money = (n: number, currency = "AUD") =>
  new Intl.NumberFormat("en-AU", { style: "currency", currency }).format(Number(n ?? 0));

function batchTone(status: string) {
  if (status === "paid") return "done" as const;
  if (status === "submitted") return "working" as const;
  if (status === "failed" || status === "error") return "stuck" as const;
  return "pending" as const;
}

/** Today in the browser's own calendar — never toISOString().slice(0,10). */
function todayLocal(): string {
  const d = new Date();
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

function monthStartLocal(): string {
  const d = new Date();
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-01`;
}

function SuperBatchesPage() {
  const { tenantId } = useMyTenantId();
  const { country } = useMyTenantCountry();
  const qc = useQueryClient();
  const enabled = !!tenantId && country === "AU";

  const fetchBatches = useServerFn(listSuperBatches);
  const batchesQ = useQuery({
    queryKey: ["au-super-batches", tenantId],
    queryFn: () => fetchBatches(),
    enabled,
  });

  const fetchSla = useServerFn(getSuperSlaSummary);
  const slaQ = useQuery({
    queryKey: ["au-super-sla", tenantId],
    queryFn: () => fetchSla({ data: { tenantId: tenantId! } }),
    enabled,
  });

  const [buildOpen, setBuildOpen] = useState(false);
  const [periodStart, setPeriodStart] = useState(monthStartLocal);
  const [periodEnd, setPeriodEnd] = useState(todayLocal);
  const [payingBatch, setPayingBatch] = useState<any | null>(null);
  const [paymentRef, setPaymentRef] = useState("");

  const refresh = () => {
    qc.invalidateQueries({ queryKey: ["au-super-batches"] });
    qc.invalidateQueries({ queryKey: ["au-super-sla"] });
  };

  const build = useServerFn(buildSuperBatch);
  const buildM = useMutation({
    mutationFn: (d: any) => build({ data: d }),
    onSuccess: () => {
      toast.success("Batch built");
      setBuildOpen(false);
      refresh();
    },
    onError: (e: any) => toast.error(e?.message ?? "Could not build the batch"),
  });

  const submit = useServerFn(submitSuperBatch);
  const submitM = useMutation({
    mutationFn: (batchId: string) => submit({ data: { batchId } }),
    onSuccess: () => {
      toast.success("Batch submitted to the clearing house");
      refresh();
    },
    onError: (e: any) => toast.error(e?.message ?? "Could not submit the batch"),
  });

  const markPaid = useServerFn(markSuperBatchPaid);
  const markPaidM = useMutation({
    mutationFn: (d: any) => markPaid({ data: d }),
    onSuccess: () => {
      toast.success("Batch reconciled as paid");
      setPayingBatch(null);
      setPaymentRef("");
      refresh();
    },
    onError: (e: any) => toast.error(e?.message ?? "Could not mark the batch paid"),
  });

  const batches = (batchesQ.data?.batches ?? []) as any[];
  const sla: any = slaQ.data;

  function downloadPayload(batch: any) {
    const blob = new Blob([JSON.stringify(batch.payload, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `super-batch-${batch.period_start}-to-${batch.period_end}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <AuComplianceShell
      title="Payday Super"
      subtitle="Superannuation guarantee contributions, batched and remitted to the clearing house"
      tenantId={tenantId}
      country={country}
      isLoading={batchesQ.isLoading}
      actions={
        <Button size="sm" onClick={() => setBuildOpen(true)}>
          <Send className="mr-1 h-4 w-4" />
          Build batch
        </Button>
      }
    >
      {() => (
        <>
          {sla ? (
            <div className="grid gap-3 sm:grid-cols-2">
              <KpiTile
                label="Overdue"
                value={money(sla.overdue.total)}
                tone={sla.overdue.count > 0 ? "stuck" : "done"}
                icon={AlertTriangle}
                hint={
                  sla.overdue.count > 0
                    ? `${sla.overdue.count} contribution${sla.overdue.count === 1 ? "" : "s"} past their due date`
                    : "Nothing past its due date"
                }
              />
              <KpiTile
                label="Due within 7 days"
                value={money(sla.dueSoon.total)}
                tone={sla.dueSoon.count > 0 ? "working" : "done"}
                hint={`${sla.dueSoon.count} contribution${sla.dueSoon.count === 1 ? "" : "s"} approaching`}
              />
            </div>
          ) : null}

          {sla?.overdue?.count > 0 ? (
            <div className="flex items-start gap-2 rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm">
              <AlertTriangle className="mt-0.5 h-4 w-4 text-destructive" />
              <div>
                <div className="font-medium text-destructive">
                  Contributions are past their payment due date
                </div>
                <div className="text-muted-foreground">
                  Under Payday Super, contributions are due within seven days of the pay date.
                  Unpaid super is not deductible and attracts the superannuation guarantee charge.
                </div>
              </div>
            </div>
          ) : null}

          <SectionCard
            title="Remittance batches"
            description="A batch groups pending contributions for a period into one SuperStream message. Build, submit, then reconcile against the payment."
          >
            {batches.length === 0 ? (
              <EmptyState
                icon={Send}
                title="No batches yet"
                description="Approve an Australian payroll run to generate contributions, then build a batch for the period to remit them."
                action={
                  <Button size="sm" onClick={() => setBuildOpen(true)}>
                    Build the first batch
                  </Button>
                }
              />
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Period</TableHead>
                    <TableHead>Due</TableHead>
                    <TableHead className="text-right">Contributions</TableHead>
                    <TableHead className="text-right">Amount</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Gateway</TableHead>
                    <TableHead className="w-56" />
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {batches.map((b) => (
                    <TableRow key={b.id}>
                      <TableCell className="font-mono text-xs">
                        {b.period_start} → {b.period_end}
                      </TableCell>
                      <TableCell className="font-mono text-xs">
                        {b.payment_due_date ?? "—"}
                      </TableCell>
                      <TableCell className="text-right tabular-nums">
                        {b.contribution_count}
                      </TableCell>
                      <TableCell className="text-right tabular-nums">
                        {money(b.total_amount)}
                      </TableCell>
                      <TableCell>
                        <StatusChip tone={batchTone(b.status)}>{b.status}</StatusChip>
                      </TableCell>
                      <TableCell className="text-xs text-muted-foreground">{b.gateway}</TableCell>
                      <TableCell>
                        <div className="flex flex-wrap gap-1">
                          {b.payload ? (
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => downloadPayload(b)}
                              title="Download the SuperStream payload"
                            >
                              <Download className="h-4 w-4" />
                            </Button>
                          ) : null}
                          {b.status === "draft" ? (
                            <Button
                              size="sm"
                              disabled={submitM.isPending}
                              onClick={() => submitM.mutate(b.id)}
                            >
                              Submit
                            </Button>
                          ) : null}
                          {b.status === "submitted" ? (
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => {
                                setPayingBatch(b);
                                setPaymentRef("");
                              }}
                            >
                              Mark paid
                            </Button>
                          ) : null}
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </SectionCard>

          <Dialog open={buildOpen} onOpenChange={setBuildOpen}>
            <DialogContent className="max-w-md">
              <DialogHeader>
                <DialogTitle>Build a remittance batch</DialogTitle>
                <DialogDescription>
                  Every pending contribution with a pay date in this period is gathered into one
                  batch. Employees with no nominated fund are not included — check Super funds →
                  Member choices first.
                </DialogDescription>
              </DialogHeader>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <Label htmlFor="period-start">Period start</Label>
                  <Input
                    id="period-start"
                    type="date"
                    value={periodStart}
                    onChange={(e) => setPeriodStart(e.target.value)}
                  />
                </div>
                <div>
                  <Label htmlFor="period-end">Period end</Label>
                  <Input
                    id="period-end"
                    type="date"
                    value={periodEnd}
                    onChange={(e) => setPeriodEnd(e.target.value)}
                  />
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setBuildOpen(false)}>
                  Cancel
                </Button>
                <Button
                  disabled={buildM.isPending || periodEnd < periodStart}
                  onClick={() => buildM.mutate({ periodStart, periodEnd })}
                >
                  {buildM.isPending ? "Building…" : "Build batch"}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>

          <Dialog open={!!payingBatch} onOpenChange={(o) => !o && setPayingBatch(null)}>
            <DialogContent className="max-w-md">
              <DialogHeader>
                <DialogTitle>Reconcile as paid</DialogTitle>
                <DialogDescription>
                  Records that the {money(payingBatch?.total_amount ?? 0)} batch has left the bank.
                  This is the step the SLA report reads, so leave it until the payment has actually
                  settled.
                </DialogDescription>
              </DialogHeader>
              <div>
                <Label htmlFor="payment-ref">Payment reference</Label>
                <Input
                  id="payment-ref"
                  value={paymentRef}
                  onChange={(e) => setPaymentRef(e.target.value)}
                  placeholder="Bank reference or clearing-house receipt"
                />
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setPayingBatch(null)}>
                  Cancel
                </Button>
                <Button
                  disabled={markPaidM.isPending}
                  onClick={() =>
                    markPaidM.mutate({
                      batchId: payingBatch.id,
                      paymentReference: paymentRef || undefined,
                    })
                  }
                >
                  {markPaidM.isPending ? "Saving…" : "Mark paid"}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </>
      )}
    </AuComplianceShell>
  );
}
